@BasicAuthentication_HostAddress = http://localhost:5231

GET {{BasicAuthentication_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{BasicAuthentication_HostAddress}}/secure
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZXN0IHRva2VuIiwibmFtZSI6InRlc3QiLCJqdGkiOiI0ZjE4NWRlMi03NTIxLTRkY2YtOGViMS05ZDMwMzk3MDk0MGUiLCJleHAiOjE3MTYxOTExNTUsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTIzMSIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTIzMSJ9.VX7DYQeXfdVj8z9HcJANQkRXegsPXEBxp1c4MUVYJI8
###
POST {{BasicAuthentication_HostAddress}}/login
Content-Type: application/json

{
    "Username":"test",
    "Password":"password"
}